### ISSUE TITLE
newsscroller on mobile devices

### ISSUE THREAD

**Issue by lck-git** [davidstutz/cmsimple-news#2]
[stylesheet.css](https://github.com/davidstutz/cmsimple-news/blob/master/css/stylesheet.css#L240)
Add white-space: nowrap; for mobile devices
```
ul.newsscroller li {
    float: left;
    margin: 0;
    padding: 0;
}
```
For more information see [CMSimple_XH-Forum](https://cmsimpleforum.com/viewtopic.php?f=16&t=12448&p=57759&sid=2cf0f98982d5950f8b88e82d4af920dc#p57679)

**Comment by davidstutz** [comment]
Danke!
